[package]
name = "rust4noobs-capstone_project"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.1"
io = "0.0.2"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
time = "0.3.41"
